services:
  postgres:
    image: postgres:17
    container_name: alumni_db_dev
    environment:
      POSTGRES_DB: alumni_db
      POSTGRES_USER: alumni_user
      POSTGRES_PASSWORD: alumni_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alumni_user -d alumni_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "4317:4317"
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - tempo

volumes:
  postgres_data:
  grafana_data: