version: '3.9'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:80" # Map local port 3000 to NGINX's port 80

  database:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ikapiar
      POSTGRES_PASSWORD: ikapiar
      POSTGRES_DB: ikapiar_staging
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: