services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ikapiar-frontend
    ports:
      - "3000:80" # Map local port 3000 to NGINX's port 80

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ikapiar-backend
    ports:
      - "4000:4000"

  database:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ikapiar-db:/var/lib/postgresql/data
volumes:
  ikapiar-db: